site_name: Laravel untuk Pemula
site_description: Panduan instalasi Laravel, Herd, dan Artisan dari nol untuk pemula
# site_url: https://NAMAUSER.github.io/NAMAREPO/
# repo_url: https://github.com/NAMAUSER/NAMAREPO

theme:
  name: material
  language: id
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Ganti ke mode gelap
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Ganti ke mode terang
  features:
    - navigation.instant
    - navigation.top
    - toc.follow
    - content.code.copy
    - search.suggest

nav:
  - Beranda: index.md
  - Windows: windows.md
  - macOS: macos.md
  - Linux: linux.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
